---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5

data_bags_path: "/home/jpereira/REPOS/chef/chefiwgc/data_bags"
suites:
  - name: default
    run_list: main::default
    attributes:
    cookbook_path: ./cookbooks/
