name             'main'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures main'
long_description 'Installs/Configures main'
version          '0.1.0'
depends 'users'
depends 'nginx'
